# Generated by Django 4.2.7 on 2023-11-18 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccessLockType', models.CharField(choices=[('1', 'Вход'), ('0', 'Выход')], max_length=1)),
                ('DateTime', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время')),
            ],
            options={
                'db_table': 'AccessLock',
                'ordering': ['-DateTime'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeviceType', models.CharField(default='Турникет', max_length=80, verbose_name='Тип устройства')),
                ('Description', models.TextField(blank=True)),
                ('Status', models.CharField(choices=[('1', 'Работает'), ('0', 'Не работает')], default='1', max_length=1, verbose_name='Состояние')),
            ],
            options={
                'db_table': 'Device',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Surname', models.CharField(max_length=80, verbose_name='Фамилия')),
                ('Name', models.CharField(max_length=80, verbose_name='Имя')),
                ('Patronymic', models.CharField(max_length=80, verbose_name='Отчество')),
                ('Job', models.CharField(max_length=80, verbose_name='Должность')),
                ('Workplace', models.CharField(max_length=150, verbose_name='Рабочее место')),
                ('PhoneNumber', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('Photo', models.CharField(max_length=200, verbose_name='Фото')),
            ],
            options={
                'db_table': 'Person',
                'ordering': ['Surname', 'Name', 'Patronymic'],
            },
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('Name', 'Surname', 'Patronymic'), name='unique person fio'),
        ),
        migrations.AddField(
            model_name='accesslock',
            name='ForeignDevice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='AccessControlApp.device'),
        ),
        migrations.AddField(
            model_name='accesslock',
            name='ForeignPerson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='AccessControlApp.person'),
        ),
    ]
